#!/usr/bin/env python3
"""Convert audited R result tables into the small static data bundle used by the site."""
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def read_csv(name):
    with (ROOT / "results" / name).open(newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def convert(row, text_fields=()):
    return {key: value if key in text_fields else float(value)
            for key, value in row.items()}


metrics = {row["key"]: float(row["value"]) for row in read_csv("metrics.csv")}
calibration = [convert(row) for row in read_csv("calibration.csv")]
coefficients = {"frequency": {}, "severity": {}}
for row in read_csv("coefficients.csv"):
    coefficients[row["model"]][row["term"]] = float(row["estimate"])
layers = [convert(row) for row in read_csv("layers.csv")]
severity_bands = [convert(row, {"band"}) for row in read_csv("severity_bands.csv")]
splits = [convert(row, {"split"}) for row in read_csv("splits.csv")]

payload = dict(metrics=metrics, calibration=calibration, coefficients=coefficients,
               layers=layers, severity_bands=severity_bands, splits=splits)
(ROOT / "data.js").write_text(
    "// Generated by build_site.py from reproducible R outputs.\n"
    "window.RISK_DATA = " + json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + ";\n",
    encoding="utf-8"
)
print("Built data.js")
